<script type="text/javascript" src="<?php echo base_url(); ?>includes/home/js/jquery-2.1.4.min.js"></script>
	<script type="text/javascript" src="<?php echo base_url(); ?>includes/home/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="<?php echo base_url(); ?>includes/home/js/owl.carousel.min.js"></script>
    <script type="text/javascript" src="<?php echo base_url(); ?>includes/home/js/chosen.jquery.min.js"></script>
    <script type="text/javascript" src="<?php echo base_url(); ?>includes/home/js/Modernizr.js"></script>
    <script type="text/javascript" src="<?php echo base_url(); ?>includes/home/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="<?php echo base_url(); ?>includes/home/js/lightbox.min.js"></script>
	<script type="text/javascript" src="<?php echo base_url(); ?>includes/home/js/masonry.pkgd.min.js"></script>
	<script type="text/javascript" src="<?php echo base_url(); ?>includes/home/js/imagesloaded.pkgd.min.js"></script>
    <script type="text/javascript" src="<?php echo base_url(); ?>includes/home/js/isotope.pkgd.min.js"></script>
	<script type="text/javascript" src="<?php echo base_url(); ?>includes/home/js/jquery.mCustomScrollbar.concat.min.js"></script>
	<script type="text/javascript" src="<?php echo base_url(); ?>includes/home/js/jquery.parallax-1.1.3.js"></script>
    <script type="text/javascript" src="<?php echo base_url(); ?>includes/home/js/jquery.magnific-popup.min.js"></script>
	<script type="text/javascript" src="<?php echo base_url(); ?>includes/home/js/masonry.js"></script>
	<script type="text/javascript" src="<?php echo base_url(); ?>includes/home/js/functions.js"></script>